export enum EventTypes {
  FOLDER_CREATED = 'FOLDER:CREATED',
  FOLDER_UPDATED = 'FOLDER:UPDATED',
  FOLDER_DELETED = 'FOLDER:DELETED',

  FOLDER_PERMISSION_GRANTED = 'FOLDER:PERMISSION:GRANTED',
  FOLDER_PERMISSION_REVOKED = 'FOLDER:PERMISSION:REVOKED',

  FILE_FILE_CREATED = 'FOLDER:FILE:CREATED',
  FILE_FILE_UPDATED = 'FOLDER:FILE:UPDATED',
  FILE_FILE_DELETED = 'FOLDER:FILE:DELETED',
  FILE_FILE_MOVED = 'FOLDER:FILE:MOVED',
}
