export enum EventTypes {
  SETTING_CHANGED = 'folder:SETTINGS_CHANGED',
  ACCESS_GRANTED = 'folder:ACCESS_GRANTED',
  ACCESS_REMOVED = 'folder:ACCESS_REMOVED',
  FILE_ADDED = 'folder:FILE_ADDED',
  FILE_REMOVED = 'folder:FILE_REMOVED',
  FILE_CHANGED = 'folder:FILE_CHANGED',
}
